# Generated by Django 4.0.1 on 2022-01-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
