# Generated by Django 4.0.1 on 2022-01-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
