# Generated by Django 4.0.1 on 2022-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_course_is_delete_profile_is_delete_student_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
