# Generated by Django 4.0.1 on 2022-01-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, default='Old brand', max_length=20),
            preserve_default=False,
        ),
    ]
