# Generated by Django 4.0.2 on 2022-02-16 17:31

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.MyUserManager()),
            ],
        ),
    ]
