# Generated by Django 4.0.1 on 2022-01-27 06:37

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, default=core.models.default_brand, help_text="The brand's name", max_length=20, validators=[core.models.brand_validator, django.core.validators.MaxLengthValidator(10, 'Shorten your brand name!')], verbose_name='Brand name'),
        ),
    ]
