# Generated by Django 4.0.1 on 2022-01-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_brand_image_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
