# Generated by Django 4.0.1 on 2022-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_brand_image_height_brand_image_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='brand/'),
        ),
    ]
