# Generated by Django 4.0.1 on 2022-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_brand_image_height_remove_brand_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
