# Generated by Django 4.0.2 on 2022-02-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app3.user')),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('app3.user',),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app3.user')),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app3.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app3.user')),
                ('blood_type', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
            bases=('app3.user',),
        ),
        migrations.CreateModel(
            name='DoctorAssistant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app3.doctor',),
        ),
    ]
