# Generated by Django 4.0.1 on 2022-01-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAssistant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app3.doctor',),
        ),
    ]
