# Generated by Django 4.0.2 on 2022-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_index=True, default=False, editable=False)),
                ('color', models.CharField(choices=[('BLK', 'Black'), ('GRE', 'Green'), ('BLU', 'Blue'), ('RED', 'Red')], default=None, max_length=3, null=True)),
                ('acceleration', models.IntegerField()),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['brand', '-acceleration'],
                'permissions': [('wash_car', 'Can wash the car'), ('destroy_car', 'Can destroy the car')],
                'db_tablespace': 'test',
            },
        ),
    ]
