# Generated by Django 4.0.1 on 2022-01-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_car_is_deleted_alter_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_deleted',
        ),
    ]
