# Generated by Django 4.0.1 on 2022-01-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
