# Generated by Django 4.0.1 on 2022-01-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand', '-acceleration']},
        ),
        migrations.AddField(
            model_name='car',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
