# Generated by Django 4.0.1 on 2022-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_car_options_car_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
