# Generated by Django 4.0.2 on 2022-02-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_car_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand', '-acceleration'], 'permissions': [('wash_car', 'Can wash the car'), ('destroy_car', 'Can destroy the car')]},
        ),
    ]
